language: cpp
env:
  - IMAGE=rrastak/dealii:ubuntu-package
services:
  - docker
before_install:
  - test -d build || mkdir build
script:
  - docker run -t -v `pwd`:/cpp-constitutive $IMAGE /bin/sh -c '
    cd cpp-constitutive/build;
    cmake ..;
    make tests;
    test/tests'

