language: cpp
env:
  - IMAGE=rrastak/dealii:ubuntu-package BUILD=Debug
  - IMAGE=rrastak/dealii:master-bare-gcc BUILD=Debug
  - IMAGE=rrastak/dealii:master-bare-gcc BUILD=Release
  - IMAGE=rrastak/dealii:master-bare-clang BUILD=Debug
  - IMAGE=rrastak/dealii:master-bare-clang BUILD=Release
services:
  - docker
script:
  - docker run --rm --tty --volume `pwd`:/cpp-constitutive $IMAGE /bin/sh -c "
    cd /cpp-constitutive &&
    cmake -DCMAKE_BUILD_TYPE=$BUILD -DDEAL_II_CXX_FLAGS='-Werror' . &&
    make tests &&
    test/tests"

