name: C++ CI

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            image: ["rrastak/dealii:ubuntu-package", "rrastak/dealii:master-bare-gcc", "rrastak/dealii:master-bare-clang"]
            build: ["Debug", "Release"]
    container: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DDEAL_II_CXX_FLAGS='-Werror' .
          make tests
    - name: Test
      run: test/tests