name: C++ CI

on: [push]

jobs:
  Unit tests:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            image: ["rrastak/dealii:ubuntu-package", "rrastak/dealii:master-bare-gcc", "rrastak/dealii:master-bare-clang"]
            build: ["Debug", "Release"]
    container: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          cmake -D CMAKE_BUILD_TYPE=${{ matrix.build }} -D CMAKE_CXX_FLAGS='-Werror' .
          make VERBOSE=ON tests
    - name: Test
      run: test/tests