name: Documentation

on: [push]

jobs:
  Documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install utilities
      run: sudo apt-get install doxygen graphviz
    - name: Generate docs
      run: |
          mkdir -p build
          cd build
          cmake ..
          make doc
    - name: Publish to Github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/html

