name: Documentation

on: [push]

jobs:
  Documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install utilities
      run: sudo apt-get install doxygen graphviz
    - name: Generate docs
      run: |
          mkdir -p build
          cd build
          cmake ..
          make doc | tee doxygen.log
          # check for warnings in the log file and raise error if there is a warning
          ! grep 'warning\|error' -q doxygen.log
    - name: Publish to Github pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/html

